In [51]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)

In [52]:
df = pd.read_pickle('dataset/cryptbars/binance_BTCUSD_ohlcv_5e6.pkl')

In [53]:
df = df.reset_index()
df

date_time     tick_num      open      high       low  \
0      2021-03-01 00:07:03.271       5211.0  45181.79  45446.48  45040.89   
1      2021-03-01 00:15:12.113      10232.0  45076.30  45600.00  45058.50   
2      2021-03-01 00:17:21.249      13624.0  45600.00  45987.01  45555.03   
3      2021-03-01 00:18:12.757      16165.0  45920.41  46317.47  45897.35   
4      2021-03-01 00:20:29.081      18633.0  46185.31  46354.34  46118.75   
...                        ...          ...       ...       ...       ...   
182383 2023-03-10 23:47:18.318  816569522.0  20250.19  20280.00  20249.31   
182384 2023-03-10 23:49:05.857  816574038.0  20280.00  20298.74  20273.45   
182385 2023-03-10 23:52:04.136  816578295.0  20284.75  20287.36  20215.08   
182386 2023-03-10 23:53:02.717  816583011.0  20215.01  20243.02  20158.77   
182387 2023-03-10 23:56:44.595  816588159.0  20183.01  20210.38  20175.56   

           close      volume  cum_ticks  cum_dollar_value  cum_plusticks  \
0       45074.91  110.558889     5211.0      5.000022e+06         2541.0   
1       45600.00  110.341998     5021.0      5.000442e+06         3049.0   
2       45920.33  109.237815     3392.0      5.005470e+06         2269.0   
3       46184.42  108.389625     2541.0      5.001970e+06         1800.0   
4       46354.34  108.204611     2468.0      5.002021e+06         1311.0   
...          ...         ...        ...               ...            ...   
182383  20280.00  247.123480     5432.0      5.007407e+06         2893.0   
182384  20284.75  246.466920     4516.0      5.000132e+06         2566.0   
182385  20215.08  247.074910     4257.0      5.003052e+06         1622.0   
182386  20181.52  248.182130     4716.0      5.009671e+06         2039.0   
182387  20192.25  247.604280     5148.0      5.000014e+06         2558.0   

        cum_plustick_volume  cum_plustick_dollar_value  vw_sqrs_prices  \
0                 57.203326               2.587390e+06    2.261271e+11   
1                 63.765218               2.890010e+06    2.266104e+11   
2                 74.473431               3.413756e+06    2.293611e+11   
3                 62.370041               2.877623e+06    2.308325e+11   
4                 57.081317               2.638612e+06    2.312309e+11   
...                     ...                        ...             ...   
182383           125.366960               2.540495e+06    1.014639e+11   
182384           171.717970               3.483897e+06    1.014389e+11   
182385            77.065170               1.561098e+06    1.013075e+11   
182386           110.578980               2.232132e+06    1.011226e+11   
182387           132.210960               2.669918e+06    1.009681e+11   

        mean_ticks_imbalance  mean_volume_imbalance  mean_dollar_imbalance  \
0                   0.005181              -0.000977             -44.172068   
1                  -0.189405              -0.003708            -167.822991   
2                  -0.220519              -0.009880            -453.471887   
3                  -0.304998              -0.006010            -276.307758   
4                  -0.035656              -0.000366             -16.694353   
...                      ...                    ...                    ...   
182383             -0.157216              -0.003020             -61.292318   
182384             -0.313109               0.023051             467.678824   
182385              0.145408               0.018539             375.079653   
182386              0.086090               0.000162               3.332125   
182387              0.004274              -0.005683            -114.777380   

        std_ticks_imbalance  std_volume_imbalance  std_dollar_imbalance  \
0                  1.000083              0.071780           3247.721775   
1                  0.981997              0.057857           2622.126366   
2                  0.975527              0.100594           4612.894591   
3                  0.952540              0.160091        

In [54]:
df["vwapret1"]=df.vwap / df.vwap.shift(1)-1
df["vwapret5"]=df.vwap / df.vwap.shift(5)-1
df["vwapret10"]=df.vwap / df.vwap.shift(10)-1
df["vwapret40"]=df.vwap / df.vwap.shift(40)-1
df.vwapret1 = df.vwapret1.shift(-1)
df.vwapret5 = df.vwapret1.shift(-5)
df.vwapret10 = df.vwapret1.shift(-10)
df.vwapret40 = df.vwapret1.shift(-40)
df

date_time     tick_num      open      high       low  \
0      2021-03-01 00:07:03.271       5211.0  45181.79  45446.48  45040.89   
1      2021-03-01 00:15:12.113      10232.0  45076.30  45600.00  45058.50   
2      2021-03-01 00:17:21.249      13624.0  45600.00  45987.01  45555.03   
3      2021-03-01 00:18:12.757      16165.0  45920.41  46317.47  45897.35   
4      2021-03-01 00:20:29.081      18633.0  46185.31  46354.34  46118.75   
...                        ...          ...       ...       ...       ...   
182383 2023-03-10 23:47:18.318  816569522.0  20250.19  20280.00  20249.31   
182384 2023-03-10 23:49:05.857  816574038.0  20280.00  20298.74  20273.45   
182385 2023-03-10 23:52:04.136  816578295.0  20284.75  20287.36  20215.08   
182386 2023-03-10 23:53:02.717  816583011.0  20215.01  20243.02  20158.77   
182387 2023-03-10 23:56:44.595  816588159.0  20183.01  20210.38  20175.56   

           close      volume  cum_ticks  cum_dollar_value  cum_plusticks  \
0       45074.91  110.558889     5211.0      5.000022e+06         2541.0   
1       45600.00  110.341998     5021.0      5.000442e+06         3049.0   
2       45920.33  109.237815     3392.0      5.005470e+06         2269.0   
3       46184.42  108.389625     2541.0      5.001970e+06         1800.0   
4       46354.34  108.204611     2468.0      5.002021e+06         1311.0   
...          ...         ...        ...               ...            ...   
182383  20280.00  247.123480     5432.0      5.007407e+06         2893.0   
182384  20284.75  246.466920     4516.0      5.000132e+06         2566.0   
182385  20215.08  247.074910     4257.0      5.003052e+06         1622.0   
182386  20181.52  248.182130     4716.0      5.009671e+06         2039.0   
182387  20192.25  247.604280     5148.0      5.000014e+06         2558.0   

        cum_plustick_volume  cum_plustick_dollar_value  vw_sqrs_prices  \
0                 57.203326               2.587390e+06    2.261271e+11   
1                 63.765218               2.890010e+06    2.266104e+11   
2                 74.473431               3.413756e+06    2.293611e+11   
3                 62.370041               2.877623e+06    2.308325e+11   
4                 57.081317               2.638612e+06    2.312309e+11   
...                     ...                        ...             ...   
182383           125.366960               2.540495e+06    1.014639e+11   
182384           171.717970               3.483897e+06    1.014389e+11   
182385            77.065170               1.561098e+06    1.013075e+11   
182386           110.578980               2.232132e+06    1.011226e+11   
182387           132.210960               2.669918e+06    1.009681e+11   

        mean_ticks_imbalance  mean_volume_imbalance  mean_dollar_imbalance  \
0                   0.005181              -0.000977             -44.172068   
1                  -0.189405              -0.003708            -167.822991   
2                  -0.220519              -0.009880            -453.471887   
3                  -0.304998              -0.006010            -276.307758   
4                  -0.035656              -0.000366             -16.694353   
...                      ...                    ...                    ...   
182383             -0.157216              -0.003020             -61.292318   
182384             -0.313109               0.023051             467.678824   
182385              0.145408               0.018539             375.079653   
182386              0.086090               0.000162               3.332125   
182387              0.004274              -0.005683            -114.777380   

        std_ticks_imbalance  std_volume_imbalance  std_dollar_imbalance  \
0                  1.000083              0.071780           3247.721775   
1                  0.981997              0.057857           2622.126366   
2                  0.975527              0.100594           4612.894591   
3                  0.952540              0.160091        

In [55]:
df.to_pickle('dataset/cryptbars/binance_BTCUSD_ohlcv_5e6_vwapret1-40_for_ns_Transformer.pkl')

In [56]:
df = pd.read_pickle('dataset/cryptbars/binance_BTCUSD_ohlcv_5e6_vwapret1-40_for_ns_Transformer.pkl')

In [57]:
df1 = df.drop(['tick_num','optimum_return','t_value_samples','t_value','vwapret5','vwapret10','vwapret40'], axis=1).dropna()
df5 = df.drop(['tick_num','optimum_return','t_value_samples','t_value','vwapret1','vwapret10','vwapret40'], axis=1).dropna()
df10 = df.drop(['tick_num','optimum_return','t_value_samples','t_value','vwapret1','vwapret5','vwapret40'], axis=1).dropna()
df40 = df.drop(['tick_num','optimum_return','t_value_samples','t_value','vwapret1','vwapret5','vwapret10'], axis=1).dropna()

In [67]:
df1

date_time      open      high       low     close  \
0      2021-03-01 00:07:03.271  45181.79  45446.48  45040.89  45074.91   
1      2021-03-01 00:15:12.113  45076.30  45600.00  45058.50  45600.00   
2      2021-03-01 00:17:21.249  45600.00  45987.01  45555.03  45920.33   
3      2021-03-01 00:18:12.757  45920.41  46317.47  45897.35  46184.42   
4      2021-03-01 00:20:29.081  46185.31  46354.34  46118.75  46354.34   
...                        ...       ...       ...       ...       ...   
182382 2023-03-10 23:44:19.974  20249.57  20257.29  20220.01  20249.71   
182383 2023-03-10 23:47:18.318  20250.19  20280.00  20249.31  20280.00   
182384 2023-03-10 23:49:05.857  20280.00  20298.74  20273.45  20284.75   
182385 2023-03-10 23:52:04.136  20284.75  20287.36  20215.08  20215.08   
182386 2023-03-10 23:53:02.717  20215.01  20243.02  20158.77  20181.52   

            volume  cum_ticks  cum_dollar_value  cum_plusticks  \
0       110.558889     5211.0      5.000022e+06         2541.0   
1       110.341998     5021.0      5.000442e+06         3049.0   
2       109.237815     3392.0      5.005470e+06         2269.0   
3       108.389625     2541.0      5.001970e+06         1800.0   
4       108.204611     2468.0      5.002021e+06         1311.0   
...            ...        ...               ...            ...   
182382  247.145290     6311.0      5.000907e+06         3234.0   
182383  247.123480     5432.0      5.007407e+06         2893.0   
182384  246.466920     4516.0      5.000132e+06         2566.0   
182385  247.074910     4257.0      5.003052e+06         1622.0   
182386  248.182130     4716.0      5.009671e+06         2039.0   

        cum_plustick_volume  cum_plustick_dollar_value  vw_sqrs_prices  \
0                 57.203326               2.587390e+06    2.261271e+11   
1                 63.765218               2.890010e+06    2.266104e+11   
2                 74.473431               3.413756e+06    2.293611e+11   
3                 62.370041               2.877623e+06    2.308325e+11   
4                 57.081317               2.638612e+06    2.312309e+11   
...                     ...                        ...             ...   
182382           128.859330               2.607618e+06    1.011918e+11   
182383           125.366960               2.540495e+06    1.014639e+11   
182384           171.717970               3.483897e+06    1.014389e+11   
182385            77.065170               1.561098e+06    1.013075e+11   
182386           110.578980               2.232132e+06    1.011226e+11   

        mean_ticks_imbalance  mean_volume_imbalance  mean_dollar_imbalance  \
0                   0.005181              -0.000977             -44.172068   
1                  -0.189405              -0.003708            -167.822991   
2                  -0.220519              -0.009880            -453.471887   
3                  -0.304998              -0.006010            -276.307758   
4                  -0.035656              -0.000366             -16.694353   
...                      ...                    ...                    ...   
182382             -0.017905              -0.004062             -82.243189   
182383             -0.157216              -0.003020             -61.292318   
182384             -0.313109               0.023051             467.678824   
182385              0.145408               0.018539             375.079653   
182386              0.086090               0.000162               3.332125   

        std_ticks_imbalance  std_volume_imbalance  std_dollar_imbalance  \
0                  1.000083              0.071780           3247.721775   
1                  0.981997              0.057857           2622.126366   
2                  0.975527              0.100594           4612.894591   
3                  0.952540              0.160091           7390.349600   
4                  0.999567              0.146366           6766.426984   
...                     ...                   ...              

In [62]:
df1.to_pickle('dataset/cryptbars/binance_BTCUSD_ohlcv_5e6_vwapret1_for_ns_Transformer.pkl')
df5.to_pickle('dataset/cryptbars/binance_BTCUSD_ohlcv_5e6_vwapret5_for_ns_Transformer.pkl')
df10.to_pickle('dataset/cryptbars/binance_BTCUSD_ohlcv_5e6_vwapret10_for_ns_Transformer.pkl')
df40.to_pickle('dataset/cryptbars/binance_BTCUSD_ohlcv_5e6_vwapret40_for_ns_Transformer.pkl')

In [45]:
df.to_pickle('dataset/cryptbars/binance_BTCUSD_ohlcv_5e6_noTval_for_ns_Transformer.pkl')

In [74]:
metrics_vwapret1 = np.load('results/binance_ohlcv_5e6_fixed_emb_vwaprep1_16x16_ns_Transformer_custom_ftMS_sl12_ll6_pl1_dm512_nh8_el2_dl1_df2048_fc3_ebfixed_dtTrue_Fixed_emb_binanceBTCUSD_bars_pred_vwaprep1_hidden16x16_0/metrics.npy')
pred_vwapret1 = np.load('results/binance_ohlcv_5e6_fixed_emb_vwaprep1_16x16_ns_Transformer_custom_ftMS_sl12_ll6_pl1_dm512_nh8_el2_dl1_df2048_fc3_ebfixed_dtTrue_Fixed_emb_binanceBTCUSD_bars_pred_vwaprep1_hidden16x16_0/pred.npy')
truth_vwapret1 = np.load('results/binance_ohlcv_5e6_fixed_emb_vwaprep1_16x16_ns_Transformer_custom_ftMS_sl12_ll6_pl1_dm512_nh8_el2_dl1_df2048_fc3_ebfixed_dtTrue_Fixed_emb_binanceBTCUSD_bars_pred_vwaprep1_hidden16x16_0/true.npy')

In [75]:
metrics_vwapret1

array([2.6475513e-01, 1.2409179e-01, 3.5226664e-01, 1.8425868e+00,
       7.1320343e+02], dtype=float32)

In [76]:
pred_vwapret1

array([[[0.08413422]],

       [[0.11205392]],

       [[0.11190587]],

       ...,

       [[0.00425813]],

       [[0.1129168 ]],

       [[0.01438035]]], dtype=float32)

In [77]:
truth_vwapret1

array([[[-0.0703566 ]],

       [[ 0.1709601 ]],

       [[ 0.50250435]],

       ...,

       [[ 0.18743275]],

       [[-0.09523859]],

       [[ 0.6883193 ]]], dtype=float32)

In [78]:
np.corrcoef(pred_vwapret1.reshape(1,-1)[0], truth_vwapret1.reshape(1,-1)[0])

array([[1.        , 0.17336812],
       [0.17336812, 1.        ]])

In [79]:
np.sum(np.where(np.sign(pred_vwapret1.reshape(1,-1)[0])==np.sign(truth_vwapret1.reshape(1,-1)[0]), 1, 0)) / len(pred)

0.5582748024582967

In [14]:
pred.reshape(1,-1)[0]

array([1.9414043 , 0.7191291 , 0.90661687, ..., 1.5140278 , 1.5301613 ,
       1.3461839 ], dtype=float32)

In [15]:
np.corrcoef(pred.reshape(1,-1)[0], truth.reshape(1,-1)[0])

array([[1.        , 0.76801216],
       [0.76801216, 1.        ]])

In [17]:
np.corrcoef(np.sign(pred.reshape(1,-1)[0]), np.sign(truth.reshape(1,-1)[0]))

array([[1.        , 0.60700426],
       [0.60700426, 1.        ]])

In [20]:
np.sum(np.where(np.sign(pred.reshape(1,-1)[0])==np.sign(truth.reshape(1,-1)[0]), 1, 0)) / len(pred)

0.803116769095698

In [21]:
metrics2 = np.load('results/binance_ohlcv_5e6_fixed_emb_32x16_ns_Transformer_custom_ftMS_sl12_ll6_pl1_dm512_nh8_el2_dl1_df2048_fc3_ebfixed_dtTrue_Fixed_emb_binanceBTCUSD_bars_pred1_hidden32x16_0//metrics.npy')

In [22]:
pred2 = np.load('results/binance_ohlcv_5e6_fixed_emb_32x16_ns_Transformer_custom_ftMS_sl12_ll6_pl1_dm512_nh8_el2_dl1_df2048_fc3_ebfixed_dtTrue_Fixed_emb_binanceBTCUSD_bars_pred1_hidden32x16_0/pred.npy')

In [23]:
truth2 = np.load('results/binance_ohlcv_5e6_fixed_emb_32x16_ns_Transformer_custom_ftMS_sl12_ll6_pl1_dm512_nh8_el2_dl1_df2048_fc3_ebfixed_dtTrue_Fixed_emb_binanceBTCUSD_bars_pred1_hidden32x16_0/true.npy')

In [24]:
metrics2

array([0.39042503, 0.3151853 , 0.56141365, 0.5742356 , 0.78303003],
      dtype=float32)

In [25]:
np.corrcoef(np.sign(pred2.reshape(1,-1)[0]), np.sign(truth2.reshape(1,-1)[0]))

array([[1.        , 0.70627965],
       [0.70627965, 1.        ]])

In [26]:
np.corrcoef(pred2.reshape(1,-1)[0], truth2.reshape(1,-1)[0])

array([[1.        , 0.82453894],
       [0.82453894, 1.        ]])

In [28]:
np.sum(np.where(np.sign(pred2.reshape(1,-1)[0])==np.sign(truth2.reshape(1,-1)[0]), 1, 0)) / len(pred2)

0.8531606672519754

In [29]:
metrics3 = np.load('results/binance_ohlcv_5e6_fixed_emb_16x16_ns_Transformer_custom_ftMS_sl12_ll6_pl1_dm512_nh8_el2_dl1_df2048_fc3_ebfixed_dtTrue_Fixed_emb_binanceBTCUSD_bars_pred1_hidden16x16_0/metrics.npy')
pred3 = np.load('results/binance_ohlcv_5e6_fixed_emb_16x16_ns_Transformer_custom_ftMS_sl12_ll6_pl1_dm512_nh8_el2_dl1_df2048_fc3_ebfixed_dtTrue_Fixed_emb_binanceBTCUSD_bars_pred1_hidden16x16_0/pred.npy')
truth3 = np.load('results/binance_ohlcv_5e6_fixed_emb_16x16_ns_Transformer_custom_ftMS_sl12_ll6_pl1_dm512_nh8_el2_dl1_df2048_fc3_ebfixed_dtTrue_Fixed_emb_binanceBTCUSD_bars_pred1_hidden16x16_0/true.npy')

In [30]:
metrics3

array([0.40133268, 0.33364454, 0.57761973, 0.5941947 , 0.8252417 ],
      dtype=float32)

In [31]:
np.corrcoef(pred3.reshape(1,-1)[0], truth3.reshape(1,-1)[0])

array([[1.        , 0.80949123],
       [0.80949123, 1.        ]])

In [32]:
np.sum(np.where(np.sign(pred3.reshape(1,-1)[0])==np.sign(truth3.reshape(1,-1)[0]), 1, 0)) / len(pred2)

0.8323639157155399

In [38]:
np.sign(pred3.reshape(1,-1)[0])>0 & np.sign(truth3.reshape(1,-1)[0])>0

TypeError: ufunc 'bitwise_and' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [39]:
np.sum(np.where((np.sign(pred3.reshape(1,-1)[0])>0) & (np.sign(truth3.reshape(1,-1)[0])>0), 1, 0)) / np.sum(np.where(np.sign(pred3.reshape(1,-1)[0])==np.sign(truth3.reshape(1,-1)[0]), 1, 0))

0.5124266596347815

In [40]:
np.sum(np.where((np.sign(pred3.reshape(1,-1)[0])<0) & (np.sign(truth3.reshape(1,-1)[0])<0), 1, 0)) / np.sum(np.where(np.sign(pred3.reshape(1,-1)[0])==np.sign(truth3.reshape(1,-1)[0]), 1, 0))

0.48757334036521854